In [2]:
import numpy as np

In [3]:
np.array([2,22,36,54,45,56,42])

array([ 2, 22, 36, 54, 45, 56, 42])

In [4]:
type(np.array([2,22,36,54,45,56,42]))

numpy.ndarray

In [5]:
l = [1,2,3,4,5]

In [6]:
np.array(l)

array([1, 2, 3, 4, 5])

In [7]:
l1 = [4,2,4,5,"Shiv", 34.325, True]

In [8]:
a1 = np.array(l1)
a1

array(['4', '2', '4', '5', 'Shiv', '34.325', 'True'], dtype='<U32')

In [9]:
a2 = np.array([[11,2,23], [4,5,6]])
a2

array([[11,  2, 23],
       [ 4,  5,  6]])

In [10]:
a3 = np.array([[[1,2,3],[4,5,6], [7,8,9]]])
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [11]:
a1.ndim

1

In [12]:
a2.ndim

2

In [13]:
a3.ndim

3

In [14]:
a1.size

7

In [15]:
a2.size

6

In [16]:
a3.size

9

In [17]:
a1.shape

(7,)

In [18]:
a2.shape

(2, 3)

In [19]:
a3.shape

(1, 3, 3)

In [20]:
np.random.randint(2,50,(2,3,4))

array([[[25, 37, 21,  5],
        [14, 37, 23, 35],
        [23, 38, 41,  7]],

       [[ 4, 22, 26, 16],
        [ 5, 22, 18,  2],
        [24,  7, 34,  8]]])

In [21]:
a4 = np.random.rand(4,4)
a4

array([[0.53836637, 0.90446257, 0.44597475, 0.46859797],
       [0.12879681, 0.61886368, 0.32691861, 0.96099631],
       [0.79635595, 0.64723138, 0.20953341, 0.85458077],
       [0.52495594, 0.25475554, 0.98057389, 0.09155407]])

# whenever you call the reshape function makesure that it is devided in equal distribution:

(4,4) = 16

(8,2) = 16

(16,1) = 16

In [22]:
a4.reshape(8,2)

array([[0.53836637, 0.90446257],
       [0.44597475, 0.46859797],
       [0.12879681, 0.61886368],
       [0.32691861, 0.96099631],
       [0.79635595, 0.64723138],
       [0.20953341, 0.85458077],
       [0.52495594, 0.25475554],
       [0.98057389, 0.09155407]])

In [23]:
a4.reshape(2,-1)

array([[0.53836637, 0.90446257, 0.44597475, 0.46859797, 0.12879681,
        0.61886368, 0.32691861, 0.96099631],
       [0.79635595, 0.64723138, 0.20953341, 0.85458077, 0.52495594,
        0.25475554, 0.98057389, 0.09155407]])

In [24]:
a4.reshape(8,-13548415)

array([[0.53836637, 0.90446257],
       [0.44597475, 0.46859797],
       [0.12879681, 0.61886368],
       [0.32691861, 0.96099631],
       [0.79635595, 0.64723138],
       [0.20953341, 0.85458077],
       [0.52495594, 0.25475554],
       [0.98057389, 0.09155407]])

In [25]:
a4.reshape(16,1)

array([[0.53836637],
       [0.90446257],
       [0.44597475],
       [0.46859797],
       [0.12879681],
       [0.61886368],
       [0.32691861],
       [0.96099631],
       [0.79635595],
       [0.64723138],
       [0.20953341],
       [0.85458077],
       [0.52495594],
       [0.25475554],
       [0.98057389],
       [0.09155407]])

# Whenever you give the negative number Numpy will automatic factorial

a4.reshape(2, -1)  ## then will consider (-1) as (8)

In [36]:
a4.reshape(2, -1)

array([[0.53836637, 0.90446257, 0.44597475, 0.46859797, 0.12879681,
        0.61886368, 0.32691861, 0.96099631],
       [0.79635595, 0.64723138, 0.20953341, 0.85458077, 0.52495594,
        0.25475554, 0.98057389, 0.09155407]])

In [39]:
a4.reshape(2, -11321649)

array([[0.53836637, 0.90446257, 0.44597475, 0.46859797, 0.12879681,
        0.61886368, 0.32691861, 0.96099631],
       [0.79635595, 0.64723138, 0.20953341, 0.85458077, 0.52495594,
        0.25475554, 0.98057389, 0.09155407]])

# cannot reshape array of size 16 into shape (1,1,1,1,1,1,1,3,2,4)


a4.reshape(1,1,1,1,1,1,1,3,2,4)

In [44]:
a4.reshape(1,1,1,1,1,1,1,2,2,4)

array([[[[[[[[[[0.53836637, 0.90446257, 0.44597475, 0.46859797],
               [0.12879681, 0.61886368, 0.32691861, 0.96099631]],

              [[0.79635595, 0.64723138, 0.20953341, 0.85458077],
               [0.52495594, 0.25475554, 0.98057389, 0.09155407]]]]]]]]]])

In [27]:
a1

array(['4', '2', '4', '5', 'Shiv', '34.325', 'True'], dtype='<U32')

In [28]:
a1[0]

'4'

In [29]:
a1[2:6]

array(['4', '5', 'Shiv', '34.325'], dtype='<U32')

In [30]:
a1[2:6:2]

array(['4', 'Shiv'], dtype='<U32')

In [31]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [32]:
a2

array([[11,  2, 23],
       [ 4,  5,  6]])

In [46]:
a2[0]

array([11,  2, 23])

In [48]:
a2[:,1:3]

array([[ 2, 23],
       [ 5,  6]])

In [47]:
a2[:,1:]

array([[ 2, 23],
       [ 5,  6]])

In [49]:
a2[:,[1,2]]

array([[ 2, 23],
       [ 5,  6]])

In [54]:
a2[[0,1], 1: ]

array([[ 2, 23],
       [ 5,  6]])

In [57]:
a5 = np.random.randint(2,90,(6,5))

In [58]:
a5

array([[24, 46, 20, 26, 52],
       [62, 89, 79, 29, 19],
       [61, 15, 38, 82, 35],
       [62, 88, 68, 81, 42],
       [77, 85, 15, 32, 37],
       [54, 48, 12, 75, 88]])

# return the all number greater than 40

In [59]:
a5[a5>40]

array([46, 52, 62, 89, 79, 61, 82, 62, 88, 68, 81, 42, 77, 85, 54, 48, 75,
       88])

In [60]:
a5[0,3]

26

In [61]:
a5[0,3] =100

In [62]:
a5

array([[ 24,  46,  20, 100,  52],
       [ 62,  89,  79,  29,  19],
       [ 61,  15,  38,  82,  35],
       [ 62,  88,  68,  81,  42],
       [ 77,  85,  15,  32,  37],
       [ 54,  48,  12,  75,  88]])

In [69]:
a6 = np.random.randint(0,3, (3,3))

In [65]:
a7 = np.random.randint(0,3, (3,3))

In [70]:
a6

array([[1, 0, 0],
       [0, 2, 0],
       [2, 1, 0]])

In [67]:
a7

array([[2, 0, 0],
       [1, 1, 0],
       [0, 0, 0]])

In [86]:
a6*a7

array([[2, 0, 0],
       [0, 2, 0],
       [0, 0, 0]])

# To do the matrix multiplication we should use the (.dot function ) or (@) between two arrays

In [87]:
a6@a7 

array([[2, 0, 0],
       [2, 2, 0],
       [5, 1, 0]])

In [88]:
a6*2

array([[2, 0, 0],
       [0, 4, 0],
       [4, 2, 0]])

In [76]:
a6/0

C:\Users\Shivaay\AppData\Local\Temp\ipykernel_9316\1058679823.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a6/0
C:\Users\Shivaay\AppData\Local\Temp\ipykernel_9316\1058679823.py:1: RuntimeWarning: invalid value encountered in true_divide
  a6/0


array([[inf, nan, nan],
       [nan, inf, nan],
       [inf, inf, nan]])

In [89]:
a8 = np.zeros((4,4))
a8

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [90]:
a9 = np.ones((4,5))
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [91]:
a9 + np.array([1,2,3,4,5])

array([[2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.]])

In [95]:
b = np.array([[1,2,3,4]]).T
b

array([[1],
       [2],
       [3],
       [4]])

In [97]:
np.array([[1,2,3,4]])

array([[1, 2, 3, 4]])

In [94]:
a9+ b

array([[2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [98]:
np.sqrt(a5)

array([[ 4.89897949,  6.78232998,  4.47213595, 10.        ,  7.21110255],
       [ 7.87400787,  9.43398113,  8.88819442,  5.38516481,  4.35889894],
       [ 7.81024968,  3.87298335,  6.164414  ,  9.05538514,  5.91607978],
       [ 7.87400787,  9.38083152,  8.24621125,  9.        ,  6.4807407 ],
       [ 8.77496439,  9.21954446,  3.87298335,  5.65685425,  6.08276253],
       [ 7.34846923,  6.92820323,  3.46410162,  8.66025404,  9.38083152]])

In [99]:
np.exp(a5)

array([[2.64891221e+10, 9.49611942e+19, 4.85165195e+08, 2.68811714e+43,
        3.83100800e+22],
       [8.43835667e+26, 4.48961282e+38, 2.03828107e+34, 3.93133430e+12,
        1.78482301e+08],
       [3.10429794e+26, 3.26901737e+06, 3.18559318e+16, 4.09399696e+35,
        1.58601345e+15],
       [8.43835667e+26, 1.65163625e+38, 3.40427605e+29, 1.50609731e+35,
        1.73927494e+18],
       [2.75851345e+33, 8.22301271e+36, 3.26901737e+06, 7.89629602e+13,
        1.17191424e+16],
       [2.83075330e+23, 7.01673591e+20, 1.62754791e+05, 3.73324200e+32,
        1.65163625e+38]])

In [100]:
np.log10(a5)

array([[1.38021124, 1.66275783, 1.30103   , 2.        , 1.71600334],
       [1.79239169, 1.94939001, 1.89762709, 1.462398  , 1.2787536 ],
       [1.78532984, 1.17609126, 1.5797836 , 1.91381385, 1.54406804],
       [1.79239169, 1.94448267, 1.83250891, 1.90848502, 1.62324929],
       [1.88649073, 1.92941893, 1.17609126, 1.50514998, 1.56820172],
       [1.73239376, 1.68124124, 1.07918125, 1.87506126, 1.94448267]])

In [101]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [102]:
list(range(0,10,2.5))

TypeError: 'float' object cannot be interpreted as an integer

In [104]:
np.arange(0,10,2.5)

array([0. , 2.5, 5. , 7.5])

In [105]:
np.arange(1.0,10.25,2.5)

array([1. , 3.5, 6. , 8.5])

In [107]:
np.linspace(2,3,num = 50,retstep= True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 0.02040816326530612)

In [116]:
np.logspace(2,3,num = 4, base = 10)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [118]:
np.eye(5)

# it creates an identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])